name: Upload

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-24.04

    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact

  upload-multiple:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        artifact: [artifact1, artifact2]
        sha: [sha1, sha2]
    steps:
      - name: Dump
        run: |
          mkdir ${{ matrix.artifact }}
          echo $GITHUB_SHA > ${{ matrix.artifact }}/${{ matrix.sha }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}
